import { v4 as uuid } from "uuid";
import { SET_ALERT, REMOVE_ALERT } from "./types";

// We can do the dispatch because of the func middleware
export const setAlert = (msg, alertType) => (dispatch) => {
  // Randomly generate the id
  const id = uuid();
  // Dispatch will add this generated object to an object state generated by redux when used  (alert reducer in this case)
  // Thanks to dispatch we can just set the type, and this type will look for its match in the index of reducers
  dispatch({
    type: SET_ALERT,
    payload: { msg, alertType, id },
  });
};
